/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnyValue,
} from '../models/index';
import {
    AnyValueFromJSON,
    AnyValueToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async getDocRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnyValue>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/doc`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnyValueFromJSON(jsonValue));
    }

    /**
     */
    async getDoc(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnyValue> {
        const response = await this.getDocRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getDocsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnyValue>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/docs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnyValueFromJSON(jsonValue));
    }

    /**
     */
    async getDocs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnyValue> {
        const response = await this.getDocsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getProxyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnyValue>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/proxy-api.yaml`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnyValueFromJSON(jsonValue));
    }

    /**
     */
    async getProxy(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnyValue> {
        const response = await this.getProxyRaw(initOverrides);
        return await response.value();
    }

}
