/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArchiveResponseResult } from './ArchiveResponseResult';
import {
    ArchiveResponseResultFromJSON,
    ArchiveResponseResultFromJSONTyped,
    ArchiveResponseResultToJSON,
} from './ArchiveResponseResult';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';

/**
 * 
 * @export
 * @interface ArchiveResponse
 */
export interface ArchiveResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof ArchiveResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {ArchiveResponseResult}
     * @memberof ArchiveResponse
     */
    result?: ArchiveResponseResult;
}

/**
 * Check if a given object implements the ArchiveResponse interface.
 */
export function instanceOfArchiveResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArchiveResponseFromJSON(json: any): ArchiveResponse {
    return ArchiveResponseFromJSONTyped(json, false);
}

export function ArchiveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : ArchiveResponseResultFromJSON(json['result']),
    };
}

export function ArchiveResponseToJSON(value?: ArchiveResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': ArchiveResponseResultToJSON(value.result),
    };
}

