/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArchiveResponseResult
 */
export interface ArchiveResponseResult {
    /**
     * 
     * @type {number}
     * @memberof ArchiveResponseResult
     */
    userID: number;
}

/**
 * Check if a given object implements the ArchiveResponseResult interface.
 */
export function instanceOfArchiveResponseResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userID" in value;

    return isInstance;
}

export function ArchiveResponseResultFromJSON(json: any): ArchiveResponseResult {
    return ArchiveResponseResultFromJSONTyped(json, false);
}

export function ArchiveResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userID': json['userID'],
    };
}

export function ArchiveResponseResultToJSON(value?: ArchiveResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userID': value.userID,
    };
}

