/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArchiveRequest
 */
export interface ArchiveRequest {
    /**
     * 
     * @type {number}
     * @memberof ArchiveRequest
     */
    userID: number;
}

/**
 * Check if a given object implements the ArchiveRequest interface.
 */
export function instanceOfArchiveRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userID" in value;

    return isInstance;
}

export function ArchiveRequestFromJSON(json: any): ArchiveRequest {
    return ArchiveRequestFromJSONTyped(json, false);
}

export function ArchiveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userID': json['userID'],
    };
}

export function ArchiveRequestToJSON(value?: ArchiveRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userID': value.userID,
    };
}

