/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResult
 */
export interface ErrorResult {
    /**
     * 
     * @type {number}
     * @memberof ErrorResult
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorResult
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorResult interface.
 */
export function instanceOfErrorResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorResultFromJSON(json: any): ErrorResult {
    return ErrorResultFromJSONTyped(json, false);
}

export function ErrorResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorResultToJSON(value?: ErrorResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
    };
}

