/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GroupMembersMembersInner } from './GroupMembersMembersInner';
import {
    GroupMembersMembersInnerFromJSON,
    GroupMembersMembersInnerFromJSONTyped,
    GroupMembersMembersInnerToJSON,
} from './GroupMembersMembersInner';

/**
 * 
 * @export
 * @interface GroupMembers
 */
export interface GroupMembers {
    /**
     * 
     * @type {Array<GroupMembersMembersInner>}
     * @memberof GroupMembers
     */
    members: Array<GroupMembersMembersInner>;
}

/**
 * Check if a given object implements the GroupMembers interface.
 */
export function instanceOfGroupMembers(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "members" in value;

    return isInstance;
}

export function GroupMembersFromJSON(json: any): GroupMembers {
    return GroupMembersFromJSONTyped(json, false);
}

export function GroupMembersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMembers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'members': ((json['members'] as Array<any>).map(GroupMembersMembersInnerFromJSON)),
    };
}

export function GroupMembersToJSON(value?: GroupMembers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'members': ((value.members as Array<any>).map(GroupMembersMembersInnerToJSON)),
    };
}

