/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface LoginResponseResult
 */
export interface LoginResponseResult {
    /**
     * 
     * @type {User}
     * @memberof LoginResponseResult
     */
    user: User;
}

/**
 * Check if a given object implements the LoginResponseResult interface.
 */
export function instanceOfLoginResponseResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function LoginResponseResultFromJSON(json: any): LoginResponseResult {
    return LoginResponseResultFromJSONTyped(json, false);
}

export function LoginResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
    };
}

export function LoginResponseResultToJSON(value?: LoginResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
    };
}

