/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutResponseResult
 */
export interface LogoutResponseResult {
    /**
     * 
     * @type {string}
     * @memberof LogoutResponseResult
     */
    id: string;
}

/**
 * Check if a given object implements the LogoutResponseResult interface.
 */
export function instanceOfLogoutResponseResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function LogoutResponseResultFromJSON(json: any): LogoutResponseResult {
    return LogoutResponseResultFromJSONTyped(json, false);
}

export function LogoutResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function LogoutResponseResultToJSON(value?: LogoutResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

