/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';
import type { ProfileUpdateResponseResult } from './ProfileUpdateResponseResult';
import {
    ProfileUpdateResponseResultFromJSON,
    ProfileUpdateResponseResultFromJSONTyped,
    ProfileUpdateResponseResultToJSON,
} from './ProfileUpdateResponseResult';

/**
 * 
 * @export
 * @interface ProfileUpdateResponse
 */
export interface ProfileUpdateResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof ProfileUpdateResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {ProfileUpdateResponseResult}
     * @memberof ProfileUpdateResponse
     */
    result?: ProfileUpdateResponseResult;
}

/**
 * Check if a given object implements the ProfileUpdateResponse interface.
 */
export function instanceOfProfileUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileUpdateResponseFromJSON(json: any): ProfileUpdateResponse {
    return ProfileUpdateResponseFromJSONTyped(json, false);
}

export function ProfileUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileUpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : ProfileUpdateResponseResultFromJSON(json['result']),
    };
}

export function ProfileUpdateResponseToJSON(value?: ProfileUpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': ProfileUpdateResponseResultToJSON(value.result),
    };
}

