/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';
import type { ProfileResponseResult } from './ProfileResponseResult';
import {
    ProfileResponseResultFromJSON,
    ProfileResponseResultFromJSONTyped,
    ProfileResponseResultToJSON,
} from './ProfileResponseResult';

/**
 * 
 * @export
 * @interface ProfileResponse
 */
export interface ProfileResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof ProfileResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {ProfileResponseResult}
     * @memberof ProfileResponse
     */
    result?: ProfileResponseResult;
}

/**
 * Check if a given object implements the ProfileResponse interface.
 */
export function instanceOfProfileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileResponseFromJSON(json: any): ProfileResponse {
    return ProfileResponseFromJSONTyped(json, false);
}

export function ProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : ProfileResponseResultFromJSON(json['result']),
    };
}

export function ProfileResponseToJSON(value?: ProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': ProfileResponseResultToJSON(value.result),
    };
}

