/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';
import type { ProfileGetResponseResult } from './ProfileGetResponseResult';
import {
    ProfileGetResponseResultFromJSON,
    ProfileGetResponseResultFromJSONTyped,
    ProfileGetResponseResultToJSON,
} from './ProfileGetResponseResult';

/**
 * 
 * @export
 * @interface ProfileGetResponse
 */
export interface ProfileGetResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof ProfileGetResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {ProfileGetResponseResult}
     * @memberof ProfileGetResponse
     */
    result?: ProfileGetResponseResult;
}

/**
 * Check if a given object implements the ProfileGetResponse interface.
 */
export function instanceOfProfileGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileGetResponseFromJSON(json: any): ProfileGetResponse {
    return ProfileGetResponseFromJSONTyped(json, false);
}

export function ProfileGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : ProfileGetResponseResultFromJSON(json['result']),
    };
}

export function ProfileGetResponseToJSON(value?: ProfileGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': ProfileGetResponseResultToJSON(value.result),
    };
}

