/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileUpdateResponseResult
 */
export interface ProfileUpdateResponseResult {
    /**
     * 
     * @type {boolean}
     * @memberof ProfileUpdateResponseResult
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ProfileUpdateResponseResult interface.
 */
export function instanceOfProfileUpdateResponseResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileUpdateResponseResultFromJSON(json: any): ProfileUpdateResponseResult {
    return ProfileUpdateResponseResultFromJSONTyped(json, false);
}

export function ProfileUpdateResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileUpdateResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function ProfileUpdateResponseResultToJSON(value?: ProfileUpdateResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

