/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface RegisterResponseResult
 */
export interface RegisterResponseResult {
    /**
     * 
     * @type {User}
     * @memberof RegisterResponseResult
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseResult
     */
    token: string;
}

/**
 * Check if a given object implements the RegisterResponseResult interface.
 */
export function instanceOfRegisterResponseResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function RegisterResponseResultFromJSON(json: any): RegisterResponseResult {
    return RegisterResponseResultFromJSONTyped(json, false);
}

export function RegisterResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'token': json['token'],
    };
}

export function RegisterResponseResultToJSON(value?: RegisterResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'token': value.token,
    };
}

