/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageToGroupRequest
 */
export interface SendMessageToGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMessageToGroupRequest
     */
    content: string;
}

/**
 * Check if a given object implements the SendMessageToGroupRequest interface.
 */
export function instanceOfSendMessageToGroupRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function SendMessageToGroupRequestFromJSON(json: any): SendMessageToGroupRequest {
    return SendMessageToGroupRequestFromJSONTyped(json, false);
}

export function SendMessageToGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageToGroupRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function SendMessageToGroupRequestToJSON(value?: SendMessageToGroupRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

