/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSettingsRequest
 */
export interface UpdateSettingsRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSettingsRequest
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the UpdateSettingsRequest interface.
 */
export function instanceOfUpdateSettingsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function UpdateSettingsRequestFromJSON(json: any): UpdateSettingsRequest {
    return UpdateSettingsRequestFromJSONTyped(json, false);
}

export function UpdateSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSettingsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function UpdateSettingsRequestToJSON(value?: UpdateSettingsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

