/* tslint:disable */
/* eslint-disable */
/**
 * Disclone Proxy API
 * Basic API proxy for Disclone
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    profileImage: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    status: string;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileImage" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileImage': json['profileImage'],
        'status': json['status'],
    };
}

export function UpdateProfileRequestToJSON(value?: UpdateProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profileImage': value.profileImage,
        'status': value.status,
    };
}

