### POST /webhooks/user/clerk/create
POST http://localhost:8000/webhooks/user/clerk/create
Content-Type: application/json

{
  "object": "event",
  "type": "user.created",
  "data": {
    "id": "usr_01",
    "primary_email_address_id": "email_01",
    "email_addresses": [
      {
        "id": "email_01",
        "email_address": "test@disclone.com"
      }
    ]
  }
}

### GET /webhooks
GET http://localhost:8000/webhooks
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yT3lVMGNGblF2UG50bFJGS2tmblFvUzVGOVkiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjE0MjAiLCJleHAiOjE2ODM4MzYzNjIsImlhdCI6MTY4MzgzNjMwMiwiaXNzIjoiaHR0cHM6Ly9jdXRlLWNpY2FkYS0yNS5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE2ODM4MzYyOTIsInNpZCI6InNlc3NfMlBmNzE3TFdkYlJNRkZkVWx5YjNkRDVYbDB4Iiwic3ViIjoidXNlcl8yT3lnbzV5ZXRWa1ZUTWtyYmhubEZRT2dXbG8ifQ.cebBVj8P1f9hjhsnda-bMPWHrBkZ9lyVLznmDvRXSxwp1CLh94WjVV833_p7zhnMF-sFMeZ5vvqWKXaaqBh2p0E9QsJf09aCUV9xrVmzsFj13w0IXwWd_i-ris5jzOVmmXewjBJPTKz2-Yc_UWQoCAdet1_wgjiG3rJ3q_l7ajt6X3jFY-D5FQZTz8oO07uqYjGUPLNFRINk6RrbWkr68almYKA9u4ujsGea2tfaabjXGU9_meLKxkUAud2Z_Jq_ZkFf-q336lJpb5KhQHeYJRNtKMInBhuIbSnRtzXNsPobt4pLwQAnCbDdo0xKGeNBTqyDmgjII_6b8MKO791BGA
X-AUTH-PROVIDER: clerk