// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package models

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Members []string `json:"members"`
	Name    string   `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt string   `json:"createdAt"`
	Id        string   `json:"id"`
	Members   []string `json:"members"`
	Name      string   `json:"name"`
	UpdatedAt string   `json:"updatedAt"`
}

// GroupMembers defines model for GroupMembers.
type GroupMembers struct {
	Members []struct {
		Id           string `json:"id"`
		ProfileImage string `json:"profileImage"`
		Status       string `json:"status"`
		Username     string `json:"username"`
	} `json:"members"`
}

// GroupMessages defines model for GroupMessages.
type GroupMessages struct {
	Items    *Message      `json:"items,omitempty"`
	Messages []interface{} `json:"messages"`
}

// Groups defines model for Groups.
type Groups struct {
	Groups []interface{} `json:"groups"`
	Items  *Group        `json:"items,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	User User `json:"User"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	Id string `json:"id"`
}

// Message defines model for Message.
type Message struct {
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
	UserId    string `json:"userId"`
}

// Profile defines model for Profile.
type Profile struct {
	Settings Settings `json:"settings"`
	User     User     `json:"user"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	User User `json:"User"`
}

// SendMessageToGroupRequest defines model for SendMessageToGroupRequest.
type SendMessageToGroupRequest struct {
	Content string `json:"content"`
}

// Settings defines model for Settings.
type Settings struct {
	Enabled bool `json:"enabled"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	ProfileImage string `json:"profileImage"`
	Status       string `json:"status"`
}

// UpdateSettingsRequest defines model for UpdateSettingsRequest.
type UpdateSettingsRequest struct {
	Enabled bool `json:"enabled"`
}

// User defines model for User.
type User struct {
	CreatedAt    string `json:"createdAt"`
	Email        string `json:"email"`
	Id           string `json:"id"`
	ProfileImage string `json:"profileImage"`
	Status       string `json:"status"`
	UpdatedAt    string `json:"updatedAt"`
	Username     string `json:"username"`
}

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// SendMessageToGroupJSONRequestBody defines body for SendMessageToGroup for application/json ContentType.
type SendMessageToGroupJSONRequestBody = SendMessageToGroupRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = UpdateSettingsRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest
