// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /doc)
	GetDoc(ctx echo.Context) error

	// (GET /docs)
	GetDocs(ctx echo.Context) error

	// (GET /groups)
	GetGroups(ctx echo.Context) error

	// (POST /groups)
	CreateGroup(ctx echo.Context) error

	// (GET /groups/{id}/)
	GetGroup(ctx echo.Context, id int64) error

	// (GET /groups/{id}/members)
	GetGroupMembers(ctx echo.Context, id int64) error

	// (GET /groups/{id}/messages)
	GetGroupMessages(ctx echo.Context, id int64) error

	// (POST /groups/{id}/messages)
	SendMessageToGroup(ctx echo.Context, id int64) error

	// (POST /login)
	Login(ctx echo.Context) error

	// (POST /logout)
	Logout(ctx echo.Context) error

	// (GET /profile)
	GetProfile(ctx echo.Context) error

	// (PATCH /profile)
	UpdateProfile(ctx echo.Context) error

	// (GET /profile/settings)
	GetSettings(ctx echo.Context) error

	// (PATCH /profile/settings)
	UpdateSettings(ctx echo.Context) error

	// (GET /proxy-api.yaml)
	GetProxy(ctx echo.Context) error

	// (POST /register)
	Register(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDoc converts echo context to params.
func (w *ServerInterfaceWrapper) GetDoc(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDoc(ctx)
	return err
}

// GetDocs converts echo context to params.
func (w *ServerInterfaceWrapper) GetDocs(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDocs(ctx)
	return err
}

// GetGroups converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroups(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroups(ctx)
	return err
}

// CreateGroup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGroup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGroup(ctx)
	return err
}

// GetGroup converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroup(ctx, id)
	return err
}

// GetGroupMembers converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroupMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroupMembers(ctx, id)
	return err
}

// GetGroupMessages converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroupMessages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroupMessages(ctx, id)
	return err
}

// SendMessageToGroup converts echo context to params.
func (w *ServerInterfaceWrapper) SendMessageToGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendMessageToGroup(ctx, id)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProfile(ctx)
	return err
}

// UpdateProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProfile(ctx)
	return err
}

// GetSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSettings(ctx)
	return err
}

// UpdateSettings converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSettings(ctx)
	return err
}

// GetProxy converts echo context to params.
func (w *ServerInterfaceWrapper) GetProxy(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProxy(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/doc", wrapper.GetDoc)
	router.GET(baseURL+"/docs", wrapper.GetDocs)
	router.GET(baseURL+"/groups", wrapper.GetGroups)
	router.POST(baseURL+"/groups", wrapper.CreateGroup)
	router.GET(baseURL+"/groups/:id/", wrapper.GetGroup)
	router.GET(baseURL+"/groups/:id/members", wrapper.GetGroupMembers)
	router.GET(baseURL+"/groups/:id/messages", wrapper.GetGroupMessages)
	router.POST(baseURL+"/groups/:id/messages", wrapper.SendMessageToGroup)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/logout", wrapper.Logout)
	router.GET(baseURL+"/profile", wrapper.GetProfile)
	router.PATCH(baseURL+"/profile", wrapper.UpdateProfile)
	router.GET(baseURL+"/profile/settings", wrapper.GetSettings)
	router.PATCH(baseURL+"/profile/settings", wrapper.UpdateSettings)
	router.GET(baseURL+"/proxy-api.yaml", wrapper.GetProxy)
	router.POST(baseURL+"/register", wrapper.Register)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZWW/UyBP/Kq3+/yVeDDML7AoN4iEcykYCEZFlX1CEOnbNTLN2t+kusxlF/u6rvsZX",
	"e8ZhM5DAvlntch2/OlxVfUVTWZRSgEBNF1dUp2somH08Eps/WV6BeWZi83ZJFx+uKG5KoAuqUXGxonWy",
	"PRFVcQGqfcIFwqp7dCFlDkzYI45QGEF1Et4ypdimTS4vPkGKtD6vE/pCAUM4VrIq38HnCjQaxUolS1DI",
	"wapcgNHBPgbuA4X7wqhgBUQI64Qq+FxxBRldfHBU50lfs4S+UkqqoSoQjnezdWQxvtbSId/UwpAdYdQ2",
	"nkWPbxKXhFZlNqpCzzyeUc8oaWneZtEoNwrCm0b7/e7uUozgUSq55DmcFGwVN1EjwyoOU6VBTQsZa/yW",
	"vCd1KyNmdtcVPbYT8NKarSAKWPNmi9j/FSzpgv5v1lSCmS8DM89qgk6e8ahSEW1W2/NJuriE2KeJZxrT",
	"47VccTFaO6BgPI9HC9P6b6myCdlsebS+2KGGLqXQMNTjvQa1DwpL0xduD0cEygrHJfJsUizHWIf4GJYp",
	"KRBEvEh9VQnbVXRclp1kE1My6DZekjy7mMWnLomHFmtA5GK1N4zPAp1X+6t8bT9MGpkxTd/BimsEdbMR",
	"f50CGNKhXQN3ZUaj8bdLjjMQmY/iP+Tu7mI8pnvCAmFcXhMmPXcIdpFDG/Ntt9TH1VPG+L+3YeyjdNSU",
	"r/8B9lSZ/k9zigXzx4PyZlDwcXKd3mk8HQ7RRewtZ9foMWJ5FvXLWMUbQmjkcLGURoMMdKp4iVwKuqDP",
	"meYpOTo9IaWSlxuylIq85DrNpTCSkKOpjjQckVNLdXR6QhP6BZR2XOYP5g/mxlRZgmAlpwv6yB6ZEoFr",
	"C9osk6ntE8CiZDzJjBKm0NNjwJcypQYNVyy0U3XJqhx72crKMuep/Xa2xiJvBp19tWQ7A1lAukCsAAmu",
	"gWQyrQoQaPlbOBwwxqrafmcM0Xss0XfElKZp88Z0OR0DasKIicR7mnjiZGjxcXjTsfnhfL7D3k/aiJhq",
	"r5cQs9a+IUEytQT7wL6ecDcURmRXAi5LSBEyAp4mocjM/6DpXU1tkTqCrpuBDcCWdABsa0amrk6Axucy",
	"29yYYZEpPGKlfU9QElduaLtmoaqgPrTfR91+m73epNfsimf1bF+SxWMgJJetpIoVgHZE/tBncvKSyKXj",
	"YTy1BEzX1BR9urAlOAzuC/eP6TowaSGylKpg6PY9vz2myWD9U5//5+4J7m5tM/Z6/Z4mgXzM/2+273+a",
	"MAgmj0aDx+xuRUWzspkWFp5+PC62BD9RYHibd0SGo7iLXYEZYU0IeBuMt8Z+DsNp97aFwc23LOMTfsQT",
	"bxoMNYjs23cuP0aomiqWyxW3EuNR+1quNOHCDwuDSLVb0gM1sZ1FcN0dqQ/t5O72NwKwha3xbULXwDLf",
	"F5wB3k+l/ItDVyBcsqK0Y/dHA+ZHDdrM2R959oxdpBn88vDR41+fklOG62ezp+R3xPKtyDdNEm63C/Wt",
	"iSVW4bqJJFnhnlCSFe6IJfP9Yb3aXrHH3Wo0vH0528K5bHbbE4b7QB1pNE63rw6GeBARMdcrdguxDpDZ",
	"fzkzf9IBxm5NOgHmzqL3QIUyukyOGO0pvtPEf8dDoZV5s/Yl0oQU3JJHcvCseXcw5Ju7rKH1QbcfJA1H",
	"oe7eaxw0EfuXJxG7A8l3SsU7HxA+GS8391nJH2yY27CP7e3t3cb1F/fhJ/vvF/cKsFJC2+V9GS5aiOfr",
	"N/bK36qO90/h3lWPNVCB4EDR3b+p/sYt+eDaOQq0o7nFDVydUA3qSxjjK5XTBV0jlovZLJcpy9dS4+LJ",
	"/MmcmlHbf96PhVdfQG1wzcWKKMiZEYmSGBlkRhwKLjCawd8qUCeDEqpBhe5FN9Qh14YfuNHXSGYiI+4O",
	"4cWaYetjP2DW5/U/AQAA///C0IObuSgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
